version: '3.8'
services:
  nextjs:
    build: ./nextjs
    container_name: nextjs_app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs
    restart: always
    command: /bin/bash -c "while [ ! -f /etc/letsencrypt/live/softhub.tn/fullchain.pem ]; do echo 'Waiting for certs...'; sleep 5; done; nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"

