version: '3.8'

services:
  nextjs:
    build: ./nextjs
    container_name: nextjs_app
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nextjs
    restart: always

